# Python Environment Setup + NumPy Basics
## Computer Vision Practice - Week 1

**Objective:** Set up a complete Python CV environment and master NumPy fundamentals.

**Deliverables:**
- Working CV environment with Anaconda, VS Code, OpenCV, PyTorch
- Jupyter notebook proficiency
- Python fundamentals review
- NumPy exercises completed

---

## PART 1: ENVIRONMENT SETUP (AM)

### Step 1: Install Anaconda
Anaconda is a Python distribution that includes package management and environment management.

**Installation Steps:**
1. Download Anaconda from https://www.anaconda.com/download
2. Run the installer and follow the setup wizard
3. Check "Add Anaconda to PATH" (optional but recommended)
4. Verify installation:
   ```bash
   conda --version
   python --version
   ```

**Why Anaconda?**
- Pre-installed scientific packages (NumPy, SciPy, Pandas, Matplotlib)
- Conda package manager for easy dependency management
- Virtual environment management built-in
- Compatible with Windows, macOS, Linux

### Step 2: Install Visual Studio Code
VS Code is a lightweight but powerful IDE for Python development.

**Installation Steps:**
1. Download VS Code from https://code.visualstudio.com/
2. Run the installer and follow the setup wizard
3. Launch VS Code
4. Install essential extensions:
   - **Python** (by Microsoft)
   - **Jupyter** (by Microsoft)
   - **Pylance** (for advanced Python IntelliSense)

**Tips:**
- Use Ctrl+Shift+X to open Extensions
- Set Python interpreter: Ctrl+Shift+P → "Python: Select Interpreter"

### Step 3: Install Essential Libraries
Install the key libraries needed for computer vision and deep learning.

**Using Conda (Recommended):**
```bash
# Create a new environment (optional)
conda create -n cv-env python=3.11

# Activate the environment
conda activate cv-env

# Install OpenCV
conda install opencv

# Install PyTorch (choose based on your GPU)
# For CPU only:
conda install pytorch torchvision torchaudio cpuonly -c pytorch

# For GPU (CUDA 12.1):
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia

# Install Jupyter
conda install jupyter jupyterlab

# Install NumPy, Pandas, Matplotlib
conda install numpy pandas matplotlib scikit-learn
```

**Verify Installation:**
```python
import cv2
import torch
import numpy as np
print("OpenCV:", cv2.__version__)
print("PyTorch:", torch.__version__)
print("NumPy:", np.__version__)
```

### Step 4: Jupyter Notebooks Setup
Jupyter notebooks allow interactive Python code execution with markdown documentation.

**Launch Jupyter:**
```bash
# From terminal in your project directory
jupyter notebook

# Or use JupyterLab (more modern)
jupyter lab
```

**Keyboard Shortcuts:**
- `Shift + Enter`: Execute cell and move to next
- `Ctrl + Enter`: Execute cell
- `A`: Insert cell above
- `B`: Insert cell below
- `D + D`: Delete cell
- `M`: Change to markdown cell
- `Y`: Change to code cell

**Notebook Best Practices:**
- Keep cells small and focused
- Document with markdown cells
- Use clear variable names
- Avoid circular dependencies

### Step 5: Python Fundamentals Refresher

#### 5.1 Lists
Lists are mutable ordered collections of items.

**Key Operations:**
- Creation: `my_list = [1, 2, 3]`
- Indexing: `my_list[0]` → 1
- Slicing: `my_list[1:3]` → [2, 3]
- Append: `my_list.append(4)`
- List comprehension: `[x**2 for x in my_list]`

In [1]:
# Example: Lists
my_list = [1, 2, 3, 4, 5]
print("Original list:", my_list)
print("First element:", my_list[0])
print("Slice [1:3]:", my_list[1:3])

# List comprehension
squared = [x**2 for x in my_list]
print("Squared:", squared)

# Append
my_list.append(6)
print("After append:", my_list)

Original list: [1, 2, 3, 4, 5]
First element: 1
Slice [1:3]: [2, 3]
Squared: [1, 4, 9, 16, 25]
After append: [1, 2, 3, 4, 5, 6]


#### 5.2 Loops and Conditionals
Control flow structures for iterating and conditional logic.

**For Loops:**
```python
for i in range(5):
    print(i)

for item in my_list:
    print(item)

for idx, value in enumerate(my_list):
    print(f"Index {idx}: Value {value}")
```

**While Loops:**
```python
count = 0
while count < 5:
    print(count)
    count += 1
```

**Conditionals:**
```python
x = 10
if x > 5:
    print("x is greater than 5")
elif x == 5:
    print("x equals 5")
else:
    print("x is less than 5")
```

In [2]:
# Example: Loops and Conditionals
print("=== For Loop ===")
for i in range(3):
    print(f"Iteration {i}")

print("\n=== Enumerate ===")
fruits = ["apple", "banana", "cherry"]
for idx, fruit in enumerate(fruits):
    print(f"{idx}: {fruit}")

print("\n=== Conditionals ===")
age = 20
if age >= 18:
    print("Adult")
else:
    print("Minor")

=== For Loop ===
Iteration 0
Iteration 1
Iteration 2

=== Enumerate ===
0: apple
1: banana
2: cherry

=== Conditionals ===
Adult


#### 5.3 Functions
Reusable blocks of code that perform specific tasks.

**Function Basics:**
```python
def greet(name):
    """This function greets a person."""
    return f"Hello, {name}!"

def add(a, b=0):
    """Add two numbers. b defaults to 0."""
    return a + b

# Calling functions
result = greet("Alice")
total = add(5, 3)
total2 = add(10)  # Uses default value
```

**Lambda Functions (Anonymous Functions):**
```python
square = lambda x: x**2
numbers = [1, 2, 3, 4, 5]
squared = list(map(square, numbers))
```

**Key Concepts:**
- Parameters vs Arguments
- Default arguments
- Return values
- Docstrings: `"""Documentation here"""`
- Scope: local vs global

In [3]:
# Example: Functions
def greet(name):
    """Greet a person by name."""
    return f"Hello, {name}!"

def multiply(a, b=1):
    """Multiply two numbers. b defaults to 1."""
    return a * b

# Call functions
print(greet("Alice"))
print(multiply(5, 3))
print(multiply(5))  # Uses default value

# Lambda function
square = lambda x: x**2
numbers = [1, 2, 3, 4, 5]
squared = list(map(square, numbers))
print("Squared:", squared)

Hello, Alice!
15
5
Squared: [1, 4, 9, 16, 25]


#### 5.4 Object-Oriented Programming (Classes)
Classes are blueprints for creating objects with attributes and methods.

**Class Basics:**
```python
class Dog:
    def __init__(self, name, age):
        """Constructor - initializes attributes."""
        self.name = name
        self.age = age
    
    def bark(self):
        """Method - action the object can perform."""
        return f"{self.name} says Woof!"
    
    def get_age(self):
        """Method to get age."""
        return self.age

# Create instance
my_dog = Dog("Buddy", 3)
print(my_dog.name)
print(my_dog.bark())
```

**Key Concepts:**
- Constructor: `__init__(self, ...)`
- `self`: Reference to the object itself
- Attributes: Data stored in the object
- Methods: Functions that belong to the object
- Inheritance: Creating subclasses from parent classes

In [4]:
# Example: Classes
class Dog:
    def __init__(self, name, age):
        """Initialize the dog with name and age."""
        self.name = name
        self.age = age
    
    def bark(self):
        """Make the dog bark."""
        return f"{self.name} says Woof!"
    
    def describe(self):
        """Describe the dog."""
        return f"{self.name} is {self.age} years old"

# Create instances
dog1 = Dog("Buddy", 3)
dog2 = Dog("Max", 5)

print(dog1.describe())
print(dog1.bark())
print(dog2.describe())
print(dog2.bark())

Buddy is 3 years old
Buddy says Woof!
Max is 5 years old
Max says Woof!


---

## PART 2: NUMPY BASICS (PM)

NumPy is the fundamental package for numerical computing in Python. It provides:
- **Efficient arrays** (homogeneous, typed)
- **Fast operations** (vectorized, compiled C code)
- **Broadcasting** (automatic shape alignment)
- **Linear algebra** operations
- **Random number** generation

**Key Differences from Lists:**
| Feature | Python List | NumPy Array |
|---------|-------------|-------------|
| Performance | Slower | Much faster |
| Memory | High overhead | Efficient |
| Operations | Element-wise loops | Vectorized |
| Type | Heterogeneous | Homogeneous |

### 2.1 Creating NumPy Arrays

NumPy arrays are the foundation of numerical computing. Here are the main ways to create them:

**From Python Lists:**
```python
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
```

**Special Array Creation Functions:**
- `np.zeros((3, 4))` - Array of zeros
- `np.ones((2, 3))` - Array of ones
- `np.arange(0, 10, 2)` - Array with range (start, stop, step)
- `np.linspace(0, 1, 5)` - Evenly spaced values
- `np.eye(3)` - Identity matrix
- `np.random.rand(3, 3)` - Random values [0, 1)
- `np.random.randn(3, 3)` - Random normal distribution

In [ ]:
import numpy as np

# Create arrays from lists
arr1 = np.array([1, 2, 3, 4, 5])
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array:", arr1)
print("2D Array:\n", arr2d)
print("Shape:", arr2d.shape)
print("Data type:", arr2d.dtype)

# Special arrays
print("\nZeros:", np.zeros((2, 3)))
print("Ones:", np.ones((2, 3)))
print("Range:", np.arange(0, 10, 2))
print("Linspace:", np.linspace(0, 1, 5)) # 5 numbers from 0 to 1
print("Identity:\n", np.eye(3)) # 3x3 identity matrix

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Data type: int64

Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]
Range: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 2.2 Indexing and Slicing

Access and manipulate array elements and subarrays.

**1D Array Indexing:**
```python
arr = np.array([0, 1, 2, 3, 4, 5])
arr[0]      # First element: 0
arr[-1]     # Last element: 5
arr[1:4]    # Slice [1:4): [1, 2, 3]
arr[::2]    # Every 2nd element: [0, 2, 4]
arr[::-1]   # Reverse: [5, 4, 3, 2, 1, 0]
```

**2D Array Indexing:**
```python
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr2d[0, 0]     # First row, first column: 1
arr2d[0, :]     # First row: [1, 2, 3]
arr2d[:, 0]     # First column: [1, 4]
arr2d[0, 1:3]   # First row, columns 1-2: [2, 3]
```

**Boolean Indexing:**
```python
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
arr[mask]       # Elements greater than 3: [4, 5]
```

In [6]:
# Indexing and Slicing Examples
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original array:", arr)
print("arr[0]:", arr[0])
print("arr[-1]:", arr[-1])
print("arr[2:5]:", arr[2:5])
print("arr[::2]:", arr[::2])
print("arr[::-1]:", arr[::-1])

# 2D Array Indexing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:\n", arr2d)
print("arr2d[0, 0]:", arr2d[0, 0])
print("arr2d[0, :]:", arr2d[0, :])
print("arr2d[:, 0]:", arr2d[:, 0])
print("arr2d[0, 1:3]:", arr2d[0, 1:3])

# Boolean Indexing
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
print("\nMask (arr > 3):", mask)
print("arr[mask]:", arr[mask])

Original array: [0 1 2 3 4 5 6 7 8 9]
arr[0]: 0
arr[-1]: 9
arr[2:5]: [2 3 4]
arr[::2]: [0 2 4 6 8]
arr[::-1]: [9 8 7 6 5 4 3 2 1 0]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d[0, 0]: 1
arr2d[0, :]: [1 2 3]
arr2d[:, 0]: [1 4 7]
arr2d[0, 1:3]: [2 3]

Mask (arr > 3): [False False False  True  True]
arr[mask]: [4 5]


### 2.3 Broadcasting

Broadcasting allows NumPy to work with arrays of different shapes automatically.

**Key Rules:**
1. If arrays have different dimensions, pad the smaller one with 1s on the left
2. Arrays are compatible if dimensions are equal or one is 1
3. The dimension with size 1 is stretched to match the other

**Examples:**
```python
# Scalar + Array
arr = np.array([1, 2, 3])
result = arr + 10      # [11, 12, 13]

# (3, 1) + (3, 4) → (3, 4)
a = np.array([[1], [2], [3]])      # Shape: (3, 1)
b = np.array([[1, 2, 3, 4]])       # Shape: (1, 4) → broadcasted to (3, 4)
result = a + b                      # Shape: (3, 4)

# (3,) → (1, 3) → (3, 3)
a = np.array([1, 2, 3])            # Shape: (3,)
b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])  # Shape: (3, 3)
result = a * b                      # Element-wise multiplication
```

**Visual Example:**
```
Shape (3, 1) + Shape (3, 4):
  [[1]        +  [[1 2 3 4]
   [2]            [5 6 7 8]
   [3]]           [9 10 11 12]]
   
   [[1 2 3 4]
 = [2 3 4 5]
    [3 4 5 6]]
```

In [7]:
# Broadcasting Examples

# Example 1: Scalar + Array
print("=== Broadcasting with Scalar ===")
arr = np.array([1, 2, 3])
result = arr + 10
print(f"Array: {arr}")
print(f"Array + 10: {result}")

# Example 2: (3, 1) + (3, 4)
print("\n=== Broadcasting (3,1) + (1,4) ===")
a = np.array([[1], [2], [3]])           # Shape: (3, 1)
b = np.array([[1, 2, 3, 4]])            # Shape: (1, 4)
print(f"a shape: {a.shape}")
print(f"b shape: {b.shape}")
result = a + b
print(f"Result shape: {result.shape}")
print(f"Result:\n{result}")

# Example 3: Array * Array
print("\n=== Broadcasting with Multiplication ===")
a = np.array([1, 2, 3])                 # Shape: (3,)
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Shape: (3, 3)
print(f"a shape: {a.shape}, b shape: {b.shape}")
result = a * b
print(f"Result:\n{result}")

=== Broadcasting with Scalar ===
Array: [1 2 3]
Array + 10: [11 12 13]

=== Broadcasting (3,1) + (1,4) ===
a shape: (3, 1)
b shape: (1, 4)
Result shape: (3, 4)
Result:
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]

=== Broadcasting with Multiplication ===
a shape: (3,), b shape: (3, 3)
Result:
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


### 2.4 Vectorized Operations

Vectorized operations perform calculations on entire arrays without explicit loops, making code faster and more readable.

**Arithmetic Operations:**
```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b       # Element-wise addition
a - b       # Element-wise subtraction
a * b       # Element-wise multiplication
a / b       # Element-wise division
a ** 2      # Power operation
```

**Aggregate Functions:**
```python
arr = np.array([1, 2, 3, 4, 5])

np.sum(arr)         # Sum of all elements: 15
np.mean(arr)        # Mean: 3.0
np.std(arr)         # Standard deviation
np.min(arr)         # Minimum: 1
np.max(arr)         # Maximum: 5
np.prod(arr)        # Product of all elements
```

**Mathematical Functions:**
```python
np.sqrt(arr)        # Square root
np.exp(arr)         # e^x
np.log(arr)         # Natural logarithm
np.sin(arr)         # Sine
np.cos(arr)         # Cosine
```

**Why Vectorized?**
- **Speed**: Implemented in C, much faster than Python loops
- **Readability**: Cleaner, more concise code
- **Memory**: Efficient use of memory

In [8]:
# Vectorized Operations Examples

# Arithmetic operations
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("=== Arithmetic Operations ===")
print(f"a: {a}")
print(f"b: {b}")
print(f"a + b: {a + b}")
print(f"a * b: {a * b}")
print(f"a ** 2: {a ** 2}")

# Aggregate functions
print("\n=== Aggregate Functions ===")
print(f"Sum: {np.sum(a)}")
print(f"Mean: {np.mean(a)}")
print(f"Std Dev: {np.std(a)}")
print(f"Min: {np.min(a)}, Max: {np.max(a)}")
print(f"Product: {np.prod(a)}")

# Mathematical functions
print("\n=== Mathematical Functions ===")
arr_small = np.array([1, 2, 3])
print(f"Array: {arr_small}")
print(f"sqrt: {np.sqrt(arr_small)}")
print(f"exp: {np.exp(arr_small)}")
print(f"sin: {np.sin(arr_small)}")
print(f"cos: {np.cos(arr_small)}")

# 2D operations
print("\n=== 2D Array Operations ===")
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Array:\n{arr2d}")
print(f"Sum along axis 0: {np.sum(arr2d, axis=0)}")
print(f"Sum along axis 1: {np.sum(arr2d, axis=1)}")
print(f"Mean: {np.mean(arr2d)}")

=== Arithmetic Operations ===
a: [1 2 3 4 5]
b: [10 20 30 40 50]
a + b: [11 22 33 44 55]
a * b: [ 10  40  90 160 250]
a ** 2: [ 1  4  9 16 25]

=== Aggregate Functions ===
Sum: 15
Mean: 3.0
Std Dev: 1.4142135623730951
Min: 1, Max: 5
Product: 120

=== Mathematical Functions ===
Array: [1 2 3]
sqrt: [1.         1.41421356 1.73205081]
exp: [ 2.71828183  7.3890561  20.08553692]
sin: [0.84147098 0.90929743 0.14112001]
cos: [ 0.54030231 -0.41614684 -0.9899925 ]

=== 2D Array Operations ===
Array:
[[1 2 3]
 [4 5 6]]
Sum along axis 0: [5 7 9]
Sum along axis 1: [ 6 15]
Mean: 3.5


In [ ]:
# Vectorized Operations Example]0ls

# Arithmetic operations
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("=== Arithmetic Operations ===")
print(f"a: {a}")
print(f"b: {b}")
print(f"a + b: {a + b}")
print(f"a * b: {a * b}")
print(f"a ** 2: {a ** 2}")

# Aggregate functions
print("\n=== Aggregate Functions ===")
print(f"Sum: {np.sum(a)}")
print(f"Mean: {np.mean(a)}")
print(f"Std Dev: {np.std(a)}")
print(f"Min: {np.min(a)}, Max: {np.max(a)}")
print(f"Product: {np.prod(a)}")

# Mathematical functions
print("\n=== Mathematical Functions ===")
arr_small = np.array([1, 2, 3])
print(f"Array: {arr_small}")
print(f"sqrt: {np.sqrt(arr_small)}")
print(f"exp: {np.exp(arr_small)}")
print(f"sin: {np.sin(arr_small)}")
print(f"cos: {np.cos(arr_small)}")

# 2D operations
print("\n=== 2D Array Operations ===")
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Array:\n{arr2d}")
print(f"Sum along axis 0: {np.sum(arr2d, axis=0)}")
print(f"Sum along axis 1: {np.sum(arr2d, axis=1)}")
print(f"Mean: {np.mean(arr2d)}")

=== Arithmetic Operations ===
a: [1 2 3 4 5]
b: [10 20 30 40 50]
a + b: [11 22 33 44 55]
a * b: [ 10  40  90 160 250]
a ** 2: [ 1  4  9 16 25]

=== Aggregate Functions ===
Sum: 15
Mean: 3.0
Std Dev: 1.4142135623730951
Min: 1, Max: 5
Product: 120

=== Mathematical Functions ===
Array: [1 2 3]
sqrt: [1.         1.41421356 1.73205081]
exp: [ 2.71828183  7.3890561  20.08553692]
sin: [0.84147098 0.90929743 0.14112001]
cos: [ 0.54030231 -0.41614684 -0.9899925 ]

=== 2D Array Operations ===
Array:
[[1 2 3]
 [4 5 6]]
Sum along axis 0: [5 7 9]
Sum along axis 1: [ 6 15]
Mean: 3.5


---

## PART 3: PRACTICAL EXERCISES

### Exercise 1: Array Creation and Exploration
Create different types of arrays and explore their properties.

**Task:**
1. Create a 1D array with values 0-10
2. Create a 3×4 matrix of random numbers
3. Create a 5×5 identity matrix
4. Print shape, dtype, and size for each array

In [9]:
# Exercise 1 Solution

# 1D array with values 0-10
arr1d = np.arange(0, 11)
print("1D Array:", arr1d)
print(f"  Shape: {arr1d.shape}, Dtype: {arr1d.dtype}, Size: {arr1d.size}")

# 3×4 matrix of random numbers
arr_random = np.random.rand(3, 4)
print("\n3×4 Random Matrix:")
print(arr_random)
print(f"  Shape: {arr_random.shape}, Dtype: {arr_random.dtype}, Size: {arr_random.size}")

# 5×5 identity matrix
arr_identity = np.eye(5)
print("\n5×5 Identity Matrix:")
print(arr_identity)
print(f"  Shape: {arr_identity.shape}, Dtype: {arr_identity.dtype}, Size: {arr_identity.size}")

1D Array: [ 0  1  2  3  4  5  6  7  8  9 10]
  Shape: (11,), Dtype: int64, Size: 11

3×4 Random Matrix:
[[0.59941985 0.91050804 0.78621544 0.35581138]
 [0.15217218 0.56878    0.38926923 0.84935467]
 [0.25815551 0.71245045 0.34665897 0.33920444]]
  Shape: (3, 4), Dtype: float64, Size: 12

5×5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
  Shape: (5, 5), Dtype: float64, Size: 25


### Exercise 2: Indexing and Slicing
Extract specific elements and subarrays from a 2D array.

**Task:**
Given a 4×5 matrix with values 1-20:
1. Extract the first row
2. Extract the last column
3. Extract elements > 10
4. Extract a 2×3 submatrix from rows 1-2, columns 2-4

In [10]:
# Exercise 2 Solution

# Create a 4×5 matrix with values 1-20
matrix = np.arange(1, 21).reshape(4, 5)
print("Original Matrix:")
print(matrix)

# 1. Extract the first row
first_row = matrix[0, :]
print(f"\nFirst row: {first_row}")

# 2. Extract the last column
last_col = matrix[:, -1]
print(f"Last column: {last_col}")

# 3. Extract elements > 10
elements_gt_10 = matrix[matrix > 10]
print(f"Elements > 10: {elements_gt_10}")

# 4. Extract 2×3 submatrix from rows 1-2, columns 2-4
submatrix = matrix[1:3, 2:5]
print(f"Submatrix (rows 1-2, cols 2-4):\n{submatrix}")

Original Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

First row: [1 2 3 4 5]
Last column: [ 5 10 15 20]
Elements > 10: [11 12 13 14 15 16 17 18 19 20]
Submatrix (rows 1-2, cols 2-4):
[[ 8  9 10]
 [13 14 15]]


### Exercise 3: Broadcasting
Use broadcasting to perform operations on arrays of different shapes.

**Task:**
1. Subtract the mean of each row from the matrix
2. Divide each column by the max value of that column
3. Create a normalized version of an array (subtract min, divide by range)

In [11]:
# Exercise 3 Solution

# Create a sample matrix
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
print("Original Data:")
print(data)

# 1. Subtract mean of each row from matrix
print("\n1. Subtract row mean:")
row_means = np.mean(data, axis=1, keepdims=True)  # Shape: (3, 1)
normalized_rows = data - row_means
print(f"Row means:\n{row_means}")
print(f"Result:\n{normalized_rows}")

# 2. Divide each column by max value
print("\n2. Divide columns by max:")
col_maxes = np.max(data, axis=0, keepdims=True)  # Shape: (1, 3)
normalized_cols = data / col_maxes
print(f"Column maxes: {col_maxes}")
print(f"Result:\n{normalized_cols}")

# 3. Normalize array (min-max normalization)
print("\n3. Min-Max Normalization:")
array = np.array([10, 20, 30, 40, 50], dtype=float)
min_val = np.min(array)
max_val = np.max(array)
normalized = (array - min_val) / (max_val - min_val)
print(f"Original: {array}")
print(f"Normalized: {normalized}")

Original Data:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

1. Subtract row mean:
Row means:
[[2.]
 [5.]
 [8.]]
Result:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]

2. Divide columns by max:
Column maxes: [[7. 8. 9.]]
Result:
[[0.14285714 0.25       0.33333333]
 [0.57142857 0.625      0.66666667]
 [1.         1.         1.        ]]

3. Min-Max Normalization:
Original: [10. 20. 30. 40. 50.]
Normalized: [0.   0.25 0.5  0.75 1.  ]


### Exercise 4: Vectorized Operations
Perform mathematical operations efficiently using vectorization.

**Task:**
1. Calculate the Euclidean distance between two vectors
2. Compute element-wise operations (sin, cos, sqrt)
3. Calculate statistics on a 2D array (mean, std, min, max along different axes)
4. Create a 10×10 multiplication table using broadcasting

In [12]:
# Exercise 4 Solution

# 1. Euclidean distance
print("1. Euclidean Distance:")
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
distance = np.sqrt(np.sum((u - v) ** 2))
print(f"Vector u: {u}")
print(f"Vector v: {v}")
print(f"Euclidean distance: {distance}")

# 2. Element-wise operations
print("\n2. Element-wise Operations:")
arr = np.array([0, np.pi/4, np.pi/2])
print(f"Array: {arr}")
print(f"sin(arr): {np.sin(arr)}")
print(f"cos(arr): {np.cos(arr)}")
print(f"sqrt(arr): {np.sqrt(arr)}")

# 3. Statistics on 2D array
print("\n3. Statistics on 2D Array:")
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Data:\n{data}")
print(f"Overall mean: {np.mean(data)}")
print(f"Overall std: {np.std(data)}")
print(f"Min along axis 0 (columns): {np.min(data, axis=0)}")
print(f"Max along axis 1 (rows): {np.max(data, axis=1)}")

# 4. 10×10 Multiplication table
print("\n4. 10×10 Multiplication Table (using broadcasting):")
a = np.arange(1, 11).reshape(10, 1)  # Column vector
b = np.arange(1, 11)                 # Row vector
mult_table = a * b
print(mult_table)

1. Euclidean Distance:
Vector u: [1 2 3]
Vector v: [4 5 6]
Euclidean distance: 5.196152422706632

2. Element-wise Operations:
Array: [0.         0.78539816 1.57079633]
sin(arr): [0.         0.70710678 1.        ]
cos(arr): [1.00000000e+00 7.07106781e-01 6.12323400e-17]
sqrt(arr): [0.         0.88622693 1.25331414]

3. Statistics on 2D Array:
Data:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Overall mean: 5.0
Overall std: 2.581988897471611
Min along axis 0 (columns): [1 2 3]
Max along axis 1 (rows): [3 6 9]

4. 10×10 Multiplication Table (using broadcasting):
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


### Exercise 5: Comprehensive Challenge
Combine Python fundamentals with NumPy in a practical scenario.

**Task: Image Normalization Class**
Create a Python class that normalizes image arrays (simulated as 2D NumPy arrays):

Requirements:
1. `__init__(self, image)` - Initialize with image array
2. `normalize(self)` - Normalize pixel values to [0, 1] range
3. `enhance_contrast(self)` - Enhance contrast by stretching to [0, 255]
4. `get_statistics(self)` - Return mean, std, min, max
5. `__str__` - Return shape and value range

In [13]:
# Exercise 5 Solution: Image Normalization Class

class ImageNormalizer:
    """Class for normalizing and enhancing image arrays."""
    
    def __init__(self, image):
        """Initialize with image array."""
        self.image = image.astype(float)  # Convert to float for operations
        self.original_range = (np.min(image), np.max(image))
    
    def normalize(self):
        """Normalize pixel values to [0, 1] range."""
        min_val = np.min(self.image)
        max_val = np.max(self.image)
        normalized = (self.image - min_val) / (max_val - min_val)
        return normalized
    
    def enhance_contrast(self):
        """Enhance contrast by stretching to [0, 255] range."""
        normalized = self.normalize()
        enhanced = normalized * 255
        return enhanced.astype(np.uint8)
    
    def get_statistics(self):
        """Return statistical information about the image."""
        return {
            'mean': np.mean(self.image),
            'std': np.std(self.image),
            'min': np.min(self.image),
            'max': np.max(self.image)
        }
    
    def __str__(self):
        """Return shape and value range."""
        return f"Image shape: {self.image.shape}, Range: {self.original_range[0]:.2f}-{self.original_range[1]:.2f}"

# Test the class
print("Testing ImageNormalizer Class:")
fake_image = np.random.randint(50, 200, size=(3, 3))
print(f"Original image:\n{fake_image}")

normalizer = ImageNormalizer(fake_image)
print(f"\n{normalizer}")

print(f"\nStatistics: {normalizer.get_statistics()}")
print(f"\nNormalized [0,1]:\n{normalizer.normalize()}")
print(f"\nEnhanced [0,255]:\n{normalizer.enhance_contrast()}")

Testing ImageNormalizer Class:
Original image:
[[143 184  68]
 [118 152 128]
 [151 180  92]]

Image shape: (3, 3), Range: 68.00-184.00

Statistics: {'mean': np.float64(135.11111111111111), 'std': np.float64(36.07228682164758), 'min': np.float64(68.0), 'max': np.float64(184.0)}

Normalized [0,1]:
[[0.64655172 1.         0.        ]
 [0.43103448 0.72413793 0.51724138]
 [0.71551724 0.96551724 0.20689655]]

Enhanced [0,255]:
[[164 255   0]
 [109 184 131]
 [182 246  52]]


---

## Summary and Next Steps

### What We Covered

✅ **Environment Setup:**
- Installed Anaconda, VS Code, and essential libraries (OpenCV, PyTorch)
- Set up Jupyter notebooks and integrated development environment

✅ **Python Fundamentals:**
- Lists: creation, indexing, slicing, list comprehensions
- Loops and Conditionals: for/while loops, if/elif/else
- Functions: definition, parameters, default arguments, lambda functions
- Classes: OOP basics, constructors, methods, attributes

✅ **NumPy Mastery:**
- Array creation: various methods and special arrays
- Indexing and Slicing: 1D/2D arrays, boolean indexing
- Broadcasting: shape alignment, vectorized operations
- Vectorized Operations: arithmetic, aggregation, mathematical functions

✅ **Practical Exercises:**
- 5 comprehensive exercises combining theory with hands-on practice

### Deliverables Completed

| Item | Status |
|------|--------|
| Working CV Environment | ✅ |
| NumPy Exercises Notebook | ✅ |
| Python Refresher Examples | ✅ |
| Jupyter Proficiency | ✅ |

### Next Steps (Week 2)

1. **Advanced NumPy:**
   - Matrix operations (dot product, matrix multiplication)
   - Linear algebra (eigenvalues, decompositions)
   - Array shape manipulation (reshape, transpose, stack)

2. **Image Processing Foundations:**
   - OpenCV basics (read, display, save images)
   - Image transformations (resize, rotate, crop)
   - Color space conversions (RGB, BGR, HSV)

3. **Introduction to Deep Learning:**
   - PyTorch tensors (relationship to NumPy arrays)
   - Autograd and automatic differentiation
   - Building simple neural networks

### Resources

- **NumPy Documentation:** https://numpy.org/doc/
- **Python Documentation:** https://docs.python.org/3/
- **OpenCV Documentation:** https://docs.opencv.org/
- **PyTorch Documentation:** https://pytorch.org/docs/

### Quick Reference

**Most Used NumPy Functions:**
```python
np.array(), np.zeros(), np.ones(), np.arange(), np.linspace()
np.shape, np.reshape, np.transpose
np.sum, np.mean, np.std, np.min, np.max
np.dot, np.matmul, np.linalg.inv
```

**Most Used Python Keywords:**
```python
def, class, for, while, if, elif, else, return, import, lambda
```

